# Generated by Django 2.1.8 on 2019-12-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhulin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(max_length=16),
        ),
    ]
