# Generated by Django 2.1.8 on 2019-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhulin', '0002_auto_20191215_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'vip'), (2, 'svip'), (3, 'vvip')], default=1),
        ),
    ]
