# Generated by Django 2.1.8 on 2019-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhulin', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='666', max_length=60),
        ),
    ]
